# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(626, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create = QtWidgets.QPushButton(self.centralwidget)
        self.create.setGeometry(QtCore.QRect(300, 400, 75, 23))
        self.create.setObjectName("create")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 71, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.stats = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.stats.setContentsMargins(0, 0, 0, 0)
        self.stats.setObjectName("stats")
        self.str_stat = StatWidget(self.verticalLayoutWidget)
        self.str_stat.setObjectName("str_stat")
        self.stats.addWidget(self.str_stat)
        self.con_stat = StatWidget(self.verticalLayoutWidget)
        self.con_stat.setObjectName("con_stat")
        self.stats.addWidget(self.con_stat)
        self.dex_stat = StatWidget(self.verticalLayoutWidget)
        self.dex_stat.setObjectName("dex_stat")
        self.stats.addWidget(self.dex_stat)
        self.int_stat = StatWidget(self.verticalLayoutWidget)
        self.int_stat.setObjectName("int_stat")
        self.stats.addWidget(self.int_stat)
        self.wis_stat = StatWidget(self.verticalLayoutWidget)
        self.wis_stat.setObjectName("wis_stat")
        self.stats.addWidget(self.wis_stat)
        self.cha_stat = StatWidget(self.verticalLayoutWidget)
        self.cha_stat.setObjectName("cha_stat")
        self.stats.addWidget(self.cha_stat)
        self.classes = QtWidgets.QComboBox(self.centralwidget)
        self.classes.setGeometry(QtCore.QRect(20, 60, 69, 22))
        self.classes.setObjectName("classes")
        self.classes_label = QtWidgets.QLabel(self.centralwidget)
        self.classes_label.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.classes_label.setObjectName("classes_label")
        self.races_label = QtWidgets.QLabel(self.centralwidget)
        self.races_label.setGeometry(QtCore.QRect(100, 40, 47, 13))
        self.races_label.setObjectName("races_label")
        self.races = QtWidgets.QComboBox(self.centralwidget)
        self.races.setGeometry(QtCore.QRect(100, 60, 69, 22))
        self.races.setObjectName("races")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Find_Replace = QtWidgets.QAction(MainWindow)
        self.action_Find_Replace.setObjectName("action_Find_Replace")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.classes_label.setBuddy(self.classes)
        self.races_label.setBuddy(self.classes)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create.setText(_translate("MainWindow", "Create"))
        self.classes_label.setText(_translate("MainWindow", "Class"))
        self.races_label.setText(_translate("MainWindow", "Race"))
        self.action_Exit.setText(_translate("MainWindow", "Exit"))
        self.action_Find_Replace.setText(_translate("MainWindow", "FindReplace"))
        self.action_About.setText(_translate("MainWindow", "About"))
from stat_widget import StatWidget
