# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stat(object):
    def setupUi(self, stat):
        stat.setObjectName("stat")
        stat.resize(209, 287)
        stat.setMinimumSize(QtCore.QSize(209, 0))
        stat.setMaximumSize(QtCore.QSize(209, 16777215))
        self.horizontalLayoutWidget = QtWidgets.QWidget(stat)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 51, 18))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.name.setEnabled(True)
        self.name.setMaximumSize(QtCore.QSize(16777215, 16777214))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.value = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.value.setFont(font)
        self.value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.value.setObjectName("value")
        self.horizontalLayout.addWidget(self.value)

        self.retranslateUi(stat)
        QtCore.QMetaObject.connectSlotsByName(stat)

    def retranslateUi(self, stat):
        _translate = QtCore.QCoreApplication.translate
        stat.setWindowTitle(_translate("stat", "Form"))
        self.name.setText(_translate("stat", "STR"))
        self.value.setText(_translate("stat", "9"))
